// Generated by scripts/nereye-gitti-fonts.py — do not edit by hand.
export const FONT_FACES = [
  { family: "Sora", weight: "400 700", file: "/nereye-gitti/fonts/sora-var.c9045ea8.woff2", bytes: 33004 },
  { family: "IBM Plex Mono", weight: "500", file: "/nereye-gitti/fonts/ibm-plex-mono-500.97d25ab1.woff2", bytes: 14768 },
] as const;
