// Generated by scripts/nereye-gitti-screenshots.mjs — do not edit by hand.
// No frames yet: gidertakip docs/magaza/ekran-goruntuleri/final/ and ham/ are empty.
export const SCREENSHOT_IMAGES: readonly { base: string; widths: readonly number[] }[] = [];
