// Generated by scripts/nereye-gitti-screenshots.mjs — do not edit by hand.
// Source: gidertakip docs/magaza/web/ (01-bas-cevir-birak, 02-maasa-kadar, 03-gunu-gelince-sorar, 04-siradaki-odeme, 05-ayin-tamami, 06-paran-nereye-gitti, og-nereye-gitti-1200x630.png)
export type ScreenshotFiles = { webp660: string; webp1320: string; jpg660: string; jpg1320: string };

export const SCREENSHOT_FILES: readonly ScreenshotFiles[] = [
  {"webp660":"/nereye-gitti/ekranlar/01-bas-cevir-birak-660.2c77accc.webp","webp1320":"/nereye-gitti/ekranlar/01-bas-cevir-birak-1320.97c52170.webp","jpg660":"/nereye-gitti/ekranlar/01-bas-cevir-birak-660.2ecc2193.jpg","jpg1320":"/nereye-gitti/ekranlar/01-bas-cevir-birak-1320.e928c5bf.jpg"},
  {"webp660":"/nereye-gitti/ekranlar/02-maasa-kadar-660.7c69793c.webp","webp1320":"/nereye-gitti/ekranlar/02-maasa-kadar-1320.83c367ef.webp","jpg660":"/nereye-gitti/ekranlar/02-maasa-kadar-660.50700737.jpg","jpg1320":"/nereye-gitti/ekranlar/02-maasa-kadar-1320.14f38ba6.jpg"},
  {"webp660":"/nereye-gitti/ekranlar/03-gunu-gelince-sorar-660.87c9e3a8.webp","webp1320":"/nereye-gitti/ekranlar/03-gunu-gelince-sorar-1320.df670089.webp","jpg660":"/nereye-gitti/ekranlar/03-gunu-gelince-sorar-660.7e502fd3.jpg","jpg1320":"/nereye-gitti/ekranlar/03-gunu-gelince-sorar-1320.eade761d.jpg"},
  {"webp660":"/nereye-gitti/ekranlar/04-siradaki-odeme-660.5d4940eb.webp","webp1320":"/nereye-gitti/ekranlar/04-siradaki-odeme-1320.2abca606.webp","jpg660":"/nereye-gitti/ekranlar/04-siradaki-odeme-660.32f5b5ea.jpg","jpg1320":"/nereye-gitti/ekranlar/04-siradaki-odeme-1320.1d3ab13e.jpg"},
  {"webp660":"/nereye-gitti/ekranlar/05-ayin-tamami-660.e8923a12.webp","webp1320":"/nereye-gitti/ekranlar/05-ayin-tamami-1320.b5ec9c0a.webp","jpg660":"/nereye-gitti/ekranlar/05-ayin-tamami-660.126e4f8b.jpg","jpg1320":"/nereye-gitti/ekranlar/05-ayin-tamami-1320.33895a5e.jpg"},
  {"webp660":"/nereye-gitti/ekranlar/06-paran-nereye-gitti-660.7bcbba90.webp","webp1320":"/nereye-gitti/ekranlar/06-paran-nereye-gitti-1320.32b5c1ce.webp","jpg660":"/nereye-gitti/ekranlar/06-paran-nereye-gitti-660.19458de5.jpg","jpg1320":"/nereye-gitti/ekranlar/06-paran-nereye-gitti-1320.1e2aed67.jpg"},
];

/** Share image (og:image / twitter:image), content-hashed. */
export const OG_IMAGE_PATH = "/nereye-gitti/og.7cd21bfb.png";
