// Generated by scripts/nereye-gitti-screenshots.mjs — do not edit by hand.
// Source: gidertakip docs/magaza/web/ at 3fe15f7 (01-bas-cevir-birak, 02-maasa-kadar, 03-gunu-gelince-sorar, 04-siradaki-odeme, 05-ayin-tamami, 06-paran-nereye-gitti)
// Each base has -660.webp, -1320.webp and a -660.jpg fallback.
export const SCREENSHOT_IMAGES: readonly string[] = [
  "/nereye-gitti/ekranlar/01-bas-cevir-birak.4cc247b3",
  "/nereye-gitti/ekranlar/02-maasa-kadar.71808638",
  "/nereye-gitti/ekranlar/03-gunu-gelince-sorar.5e9f960d",
  "/nereye-gitti/ekranlar/04-siradaki-odeme.92b10b61",
  "/nereye-gitti/ekranlar/05-ayin-tamami.893d11ff",
  "/nereye-gitti/ekranlar/06-paran-nereye-gitti.0a6eed44",
];
